@startuml
[*] --> メニュー画面
state c <<choice>>
メニュー画面 --> c
c --> 予約と確認画面 : 予約と確認ボタンを押す
予約と確認画面 --> あなたの順番画面 : 登録ボタンを押す
あなたの順番画面 --> 予約と確認画面 : メニューボタンを押す
あなたの順番画面 --> [*] : 現在の順番を表示する
c --> 今の順番画面 : 今の順番ボタンを押す
今の順番画面 --> [*] : 今の順番を表示する
@enduml