@startuml
left to right direction
actor 患者
actor 看護師
rectangle 診察予約システム{
    usecase 予約をする
    usecase あなたの順番を確認する
    usecase 予約を取り消す
    usecase 患者の番号を更新する
} 
患者 --> 予約をする
患者 --> あなたの順番を確認する
患者 --> 予約を取り消す
看護師 --> 患者の番号を更新する
@enduml



