@startuml
actor 客
actor ベンダー

rectangle 自動販売機{
    usecase 自動販売機
    usecase お金を入れる
    usecase ボタンをおす
    usecase ドリンクを出す
}

客-->お金を入れる
お金を入れる-->自動販売機
自動販売機-->ボタンを押す
ボタンを押す-->ベンダー
ベンダー-->ドリンクを出す
ドリンクを出す-->自動販売機

@enduml